//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dash_Board.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connect", ReplyAction="http://tempuri.org/IService1/ConnectResponse")]
        string Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Connect", ReplyAction="http://tempuri.org/IService1/ConnectResponse")]
        System.Threading.Tasks.Task<string> ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/APKDetails", ReplyAction="http://tempuri.org/IService1/APKDetailsResponse")]
        string APKDetails(string RecepientType, string MachineGroup, string MachineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/APKDetails", ReplyAction="http://tempuri.org/IService1/APKDetailsResponse")]
        System.Threading.Tasks.Task<string> APKDetailsAsync(string RecepientType, string MachineGroup, string MachineName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PLCData", ReplyAction="http://tempuri.org/IService1/PLCDataResponse")]
        string PLCData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PLCData", ReplyAction="http://tempuri.org/IService1/PLCDataResponse")]
        System.Threading.Tasks.Task<string> PLCDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RAJU", ReplyAction="http://tempuri.org/IService1/RAJUResponse")]
        string RAJU();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RAJU", ReplyAction="http://tempuri.org/IService1/RAJUResponse")]
        System.Threading.Tasks.Task<string> RAJUAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Dash_Board.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Dash_Board.ServiceReference1.IService1>, Dash_Board.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Connect() {
            return base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task<string> ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public string APKDetails(string RecepientType, string MachineGroup, string MachineName) {
            return base.Channel.APKDetails(RecepientType, MachineGroup, MachineName);
        }
        
        public System.Threading.Tasks.Task<string> APKDetailsAsync(string RecepientType, string MachineGroup, string MachineName) {
            return base.Channel.APKDetailsAsync(RecepientType, MachineGroup, MachineName);
        }
        
        public string PLCData() {
            return base.Channel.PLCData();
        }
        
        public System.Threading.Tasks.Task<string> PLCDataAsync() {
            return base.Channel.PLCDataAsync();
        }
        
        public string RAJU() {
            return base.Channel.RAJU();
        }
        
        public System.Threading.Tasks.Task<string> RAJUAsync() {
            return base.Channel.RAJUAsync();
        }
    }
}
